"use client";
import type { CustomerPayments } from "@hyd/contracts";
import { useEffect, useState } from "react";
import { apiFetch } from "@/lib/api";
import { useCustomerData } from "../customer-data";
import styles from "../customer.module.css";
const money=(value:string|number)=>`₹${Number(value).toLocaleString("en-IN")}`;
type CheckoutResponse={razorpay_payment_id:string;razorpay_order_id:string;razorpay_signature:string};
type RazorpayOptions={key:string;amount:number;currency:string;name:string;description:string;order_id:string;prefill:{name:string;contact:string};handler:(response:CheckoutResponse)=>void;theme:{color:string};modal:{ondismiss:()=>void}};
declare global{interface Window{Razorpay:new(options:RazorpayOptions)=>{open():void}}}
export default function PaymentsPage(){
  const {data,message:customerMessage}=useCustomerData();const [ledger,setLedger]=useState<CustomerPayments|null>(null),[message,setMessage]=useState("Loading transactions…"),[busy,setBusy]=useState(false),[amount,setAmount]=useState(0);
  useEffect(()=>{void apiFetch<CustomerPayments>("/payments/customer/me").then(result=>{setLedger(result);setAmount(Number(result.pendingAmount));setMessage("");}).catch(error=>setMessage(error instanceof Error?error.message:"Payments could not be loaded."));},[]);
  async function pay(){if(!data||!ledger||amount<=0)return;setBusy(true);setMessage("Preparing secure checkout…");try{await loadCheckout();const order=await apiFetch<{keyId:string;orderId:string;amount:number;currency:string}>("/payments/razorpay/orders",{method:"POST",body:JSON.stringify({amount})});new window.Razorpay({key:order.keyId,amount:order.amount,currency:order.currency,name:"Sri Sai Anu Motor Driving School",description:data.enrollment.courseName,order_id:order.orderId,prefill:{name:data.customer.displayName,contact:data.customer.phone},theme:{color:"#e4ff33"},modal:{ondismiss:()=>{setBusy(false);setMessage("Checkout closed. No payment was recorded.");}},handler:response=>{void apiFetch("/payments/razorpay/verify",{method:"POST",body:JSON.stringify({razorpayOrderId:response.razorpay_order_id,razorpayPaymentId:response.razorpay_payment_id,razorpaySignature:response.razorpay_signature})}).then(()=>window.location.reload()).catch(error=>{setBusy(false);setMessage(error instanceof Error?error.message:"Payment verification failed.");});}}).open();}catch(error){setBusy(false);setMessage(error instanceof Error?error.message:"Secure checkout could not start.");}}
  if(!data||!ledger)return <p className={styles.state}>{customerMessage||message}</p>;
  const e=data.enrollment;return <div className={styles.page}><header className={styles.pageTitle}><h1>Payments</h1><p>Every verified payment, receipt and refund is reconciled against your course balance.</p></header><section className={styles.paymentStatement}><div><span>Course price</span><b>{money(e.price)}</b></div><div><span>Discount</span><b>−{money(e.discount)}</b></div><div><span>Total payable</span><b>{money(e.totalPayable)}</b></div><div><span>Verified paid</span><b>{money(ledger.paidAmount)}</b></div><div className={styles.balance}><span>Pending balance</span><strong>{money(ledger.pendingAmount)}</strong></div></section>{Number(ledger.pendingAmount)>0&&<section className={styles.onlinePayment}><div><h2>Pay securely online</h2><p>Enter a partial amount or pay the full pending balance through Razorpay.</p></div><label>Amount<input type="number" min="1" max={ledger.pendingAmount} step="0.01" value={amount} onChange={event=>setAmount(Number(event.target.value))}/></label><button disabled={busy||amount<1||amount>Number(ledger.pendingAmount)} onClick={()=>void pay()}>{busy?"Opening checkout…":`Pay ${money(amount)}`}</button></section>}<section className={styles.customerReceipts}><h2>Receipts</h2>{ledger.payments.map(payment=><article key={payment.id}><div><b>{payment.receiptNumber}</b><strong>{money(payment.amount)}</strong><small>{payment.method.replace("_"," ")} · {new Date(payment.verifiedAt??payment.createdAt).toLocaleDateString("en-IN")}</small></div><span>{payment.status.replace("_"," ")}{Number(payment.refundedAmount)>0&&<small>{money(payment.refundedAmount)} refunded</small>}</span></article>)}{!ledger.payments.length&&<p className={styles.empty}>No verified payments yet.</p>}</section><p className={styles.paymentNote} role="status">{message}</p></div>;
}
function loadCheckout(){if(window.Razorpay)return Promise.resolve();return new Promise<void>((resolve,reject)=>{const script=document.createElement("script");script.src="https://checkout.razorpay.com/v1/checkout.js";script.onload=()=>resolve();script.onerror=()=>reject(new Error("Razorpay checkout could not be loaded"));document.head.appendChild(script);});}
