"use client";
import Link from "next/link";
import { useCustomerData } from "./customer-data";
import styles from "./customer.module.css";
const date = (value: string | null) => value ? new Date(value).toLocaleDateString("en-IN", { day: "numeric", month: "short", year: "numeric" }) : "Not started";
export default function CustomerHome() {
  const { data, message } = useCustomerData(); if (!data) return <p className={styles.state}>{message}</p>; const { enrollment: e } = data;
  return <div className={styles.page}><section className={styles.welcome}><div><span>{e.courseName}</span><h1>Hello, {data.customer.displayName.split(" ")[0]}</h1><p>Your class and kilometre record updates whenever a lesson is completed.</p></div><div className={styles.deadline}><span>{e.status === "EXPIRED" ? "Training window expired" : e.firstLessonAt ? "Days remaining" : "Training window"}</span><strong>{e.firstLessonAt ? e.daysRemaining : "Starts after class 1"}</strong><small>{e.deadlineAt ? `Deadline ${date(e.deadlineAt)}` : "60 days from your first completed class"}</small></div></section>
    <section className={styles.metrics}><div><span>Classes</span><strong>{e.classesCompleted}<small> / {e.classesTotal}</small></strong><p>{e.classesRemaining} remaining</p></div><div><span>Kilometres</span><strong>{e.completedKm}<small> km</small></strong><p>{e.pendingKm} km pending</p></div><div><span>Payments</span><strong>₹{Number(e.paid).toLocaleString("en-IN")}</strong><p>₹{Number(e.pendingAmount).toLocaleString("en-IN")} pending</p></div></section>
    <section className={styles.timeline}><h2>Your course</h2><dl><div><dt>First class</dt><dd>{date(e.firstLessonAt)}</dd></div><div><dt>Current deadline</dt><dd>{date(e.deadlineAt)}</dd></div><div><dt>Status</dt><dd>{e.status.replace("_", " ")}</dd></div></dl>{data.deadlineExtensions[0] && <p>Deadline extended from {date(data.deadlineExtensions[0].previousDeadline)}. Reason: {data.deadlineExtensions[0].reason}</p>}</section>
    {(Number(e.pendingKm)>0||Number(e.pendingAmount)>0||e.status==="EXPIRED")&&<section className={styles.customerAttention}><span>NEEDS ATTENTION</span>{e.status==="EXPIRED"&&<p>Your training window has expired. Contact the school before your next class.</p>}{Number(e.pendingKm)>0&&<p><strong>{e.pendingKm} km</strong> remains pending from earlier classes.</p>}{Number(e.pendingAmount)>0&&<p><strong>₹{Number(e.pendingAmount).toLocaleString("en-IN")}</strong> remains payable.</p>}</section>}
    <section className={styles.next}><h2>Review your record</h2><Link href="/customer/history">See every class <span>→</span></Link><Link href="/customer/kilometres">Trace pending KM <span>→</span></Link><Link href="/customer/payments">Check payment balance <span>→</span></Link><Link href="/customer/complaints">Track complaints <span>→</span></Link></section></div>;
}
